---
 - name: Handler Demo
   hosts: redhat
   force_handlers: yes
   tasks:
     - name: My tasks are dependet on the handler
       yum: name=httpd state=present
       notify: Change the content
   handlers:
     - name: Change the content
       debug:
         msg: "Handler is running"
