---
- name: This is my tasks for testing
  hosts: redhat,ubuntu
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: install apache (apt)
      when: ansible_distribution == "Ubuntu"
      package:
        name: apache2
        state: present
    - name: install apache (yum)
      when: ansible_distribution == "Amazon"
      package:
        name: httpd
        state: present
