# This is the playbook to implement the internal webservice
---
 - name: Enabling the internal web-service
   hosts: redhat
   become: yes
   tasks:
     - name: Install httpd and firewalld
       yum:
         name:
           - httpd
           - firewalld
         state: present
     - name: Enable the and run firewalld
       service:
         name: firewalld
         enabled: yes
         state: started
     - name: firewalld permitted httpd service
       firewalld:
         permanent: yes
         state: enabled
         port: 80/tcp
         immediate: yes
     - name: httpd enabled and running
       service:
         name: httpd
         enabled: yes
         state: started
     - name: test html page
       copy:
         content: "Welcome to the Ansible batch No-2!\n"
         dest: /var/www/html/index.html
