---
 - name: Handler Demo
   hosts: redhat
   tasks:
     - name: My tasks are dependet on the handler
       yum: name=httpd state=absent
       notify: Change the content
   handlers:
     - name: Change the content
       copy: dest=/var/www/html/index.html content="This is content given by handlers"

